{% set version = "5.45.0" %}
{% set name = "maxima" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://sourceforge.net/projects/maxima/files/Maxima-source/{{ version }}-source/{{ name }}-{{ version }}.tar.gz
  sha256: c7631f32644805cebb7bafef3ab5331c4bacd2c27e384fd88323b5039a60d0d8
  patches:
    # Patches from https://git.sagemath.org/sage.git/tree/build/pkgs/maxima/patches
    # Fixes a test failure that can occur when the install tree has been
    # relocated; see https://trac.sagemath.org/ticket/11348
    - patches/infodir.patch
    # Fixes a bug in matrix inversion that affects Sage; see
    # https://sourceforge.net/p/maxima/bugs/2596/
    - patches/matrixexp.patch
    # Fixes a regression in printing that causes test failures in Sage, and
    # has not been reverted yet; see https://trac.sagemath.org/ticket/13364#comment:89
    - patches/undoing_true_false_printing_patch.patch
    # Disables a few tests that currently do not pass, see #14
    - patches/osx_tests.patch
    # Build a fasl library for ecl
    - patches/maxima.system.patch
    # Disable test that fails with ecl 16.1.2 in some setups
    - patches/rtest8.patch
    # Disable tests that started fails in 5.42.2
    - patches/disable_5_42_2_tests.diff

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - libtool
    - texinfo
    - make
  host:
    - ecl 20.4.*
    - readline
    - gmp
  run:
    - readline
    - {{ pin_compatible('ecl', max_pin='x.x.x') }}
    - gmp

test:
  files:
    - run-from-ecl.lisp
  commands:
    - maxima --version
    - ecl -shell run-from-ecl.lisp

about:
  home: http://maxima.sourceforge.net/
  license: GPLv2+
  license_file: COPYING
  summary: Maxima is a system for the manipulation of symbolic and numerical expressions.
  doc_url: http://maxima.sourceforge.net/documentation.html
  dev_url: https://sourceforge.net/p/maxima/code/ci/master/tree/

extra:
  recipe-maintainers:
    - embray
    - isuruf
    - saraedum
