# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MxeJ7FoY696ml+BOYCQmkIxQ68tUClE9530e+WKsH5avEw3PIm4VXap+Auib+M+Zb9G4VFJfgzZI7J3T23aYTNcinoeMi74CcfS/82xDrZ08xG12j6f5Z33ERvygR6JvqqCNLg6wkJ7rtKHjUnwWTp1nWAjDOms0hVBJk9lmso87+wF3MrK7ZGn4wUxhlHc+RFUVlLfJ4a3GEgIj/bwKGW8tOIBfBMrBVRU7FCQibxPbLTXplYEx7WP6LQ3XUi9VkyLKErXowWNxx2H0bj9kwkEjLdYfYsYDqzIc0eZkw2UY5G7OKJFtGwODV2lPvHx6oFBZuYhTduzrNYuNAlqcRTK5BDKUaInGmslzsESk58F+sYjbRbN8qkJuqp5+jFQyDtRLrZa2P2fuuq12d6izP0e7lpctd9QDeR0NwmgQRrG75OltvUj9MAS5bmf7URaJW/jELOCt+3ILC9q12FIzTZwGRBILoQUGVMA4lCLX5fAzaNv3rmun+8qRTzByvXQl9qrIuJmzI38jaRSjonN73Z4dZvQx5Zqh+rEIPANAQaEDmxpFaO+EzJ5UsWxY1gM3UR6/KpR6DAzv9/rfVjWM++AcEkW0AswVSWjScsX5Ptf36IHd4LaMNcIMEhT59UeEiI37sMWQv9pum7J5+4E/U6LcM37yHS/r1TPX4HCW4Es="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
