travis:
  secure:
    BINSTAR_TOKEN: FSYID8n1lu7C20OvlplgXqe+4OA95kwJF9ikuZOxBKyCSf4oCbhBJCu9tBtxDqlzURVeCzy8U/rCpWmaf5zD+FpOzZmY9gFbtoUsYTf1fu/vOOeJBoZ0OlX6xHSukCTIQ4uHOCg/FvbcNTM/sONLpx9NprVw1WyFY5/pJC7U+sHC/sOguHErwZlEpVwbwu1GKhOW59qaBXUxCi+EkXQ5ZxDpZpuyvFzLoo9p5IF1BaWvUoAMiI+X7l7Y6PdbttZBlsX/MW64jaQssMNOUNVlEzhqdsXhkyxUueOeTpBQKuFmOZkz+o2aG6xn4LkTxmd1kmbQzn86qlVAvfeBu3nEMOmMv3zADx75ZmSkXvD8DZpMpS/EWq6qkOLXPIBYNvbAIMIg95E8bS8CUKZOwL/tIioDi/dP2ves1xuyoUMfh7iTwkb6xFxe1rhGEeyRbeMZwcSxNTsciMm3t/vUs4WqX9+oMVMaE/nx0V3TWjeR1c37GnMBvsTDu8YxyIdRm4JwxB8rtFZIL+qu5tLaODToR8pzgxIqlfiJZBkkfFQxpi2T9egPGptFYsiSa5NH27nZvRnC5Oh6CkAwxQ7qnQPqMg9KQlOgdzMWs6t/ELDV5C8TOkFHCvLvnavKziKpnHRT9j1XcsLU1r+gtQ6pHHCOdeN6x0aPcNtCzSUKLHUHmyM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
