appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: t4hHLcfO7HCYzDtSwFP0ODJkWkRiOYixpQB2JuZxY+TuWNvb94Vhd9ce6l3WBGvCGSG7G5uh3rpZIyy8W84SfDFinOld6FXbuflSH5ruPIcYIrTJgpbPwbx1J81uMxg9S+720Bq3JzEScxsm7MZaoydtENrK6l0s+OLcVuYrvU1htYBT4TZDj8F7d+wnT8PWw5xMYoBt8tn6/a7gMgm/9Hw8wDIzXdKrPjnb/OSikoUcyP31bDLuDaWQSgkRHlErDPo4EyaFTfRccOrrI/WVNixHcRGgK1BuHLA6Tc+pCB+unB8fqekosPDQ3KtpO6CJoPISpuqc3YuGr5F3yfbppJAldpsE7ZCIkQuad3HnndB0uN6TQfqLECR8yULAH+PuqmjJqA8WAASyVoRh/vlkIjMH2fFCMRNpPWBP5awYvG9NAYCvuKNdJcZLmERVdY9GPKz/UiN14oUBBtRju74D/wJVgH1xV+HjCqPAPbzzDOicC9uVpJaTrqOAXhUegeAhHf/E3U7aOLD/5di0xGAzGoWwNJzETjbKNJNHkzvZAA/suAsZFEynkoWsCb3RxbQYdYti26WOpAFg5jvc4ivyIEFNZGjJDpUXlSZWBNPrggcOlbzsGdcSdf2wVz9Mh1uof38v0aUP6ZRU2qMGCIqFgzEbS/e5cTGdNtakCAtORbI=}
