travis:
  secure:
    BINSTAR_TOKEN: qpAHURY0xIh6Bd7LKXusMvvEoVh27+BaFG5CRzad88DcKAq0eg0+vsVws4JmpOCqc8T9xevqNhezwYAQKKktM/Ux1tTuPghAQU7pacO8iQ8qqUG7AIkWSFMxDzgaaUTLVhtBDmJokcdJE8mcJrvywEdhQQioIlnQG1MlS5hRUbDUuqKGC0DA0B9m3Xvd+3axD+J0RvAhSb2/6pOhaxVvpYxHUmsa8LnA0uDOanFo96wT6jcNBpytu+A/lYvE8NjWrqIZsUs9L/VFUpYasWU0Zg3WyU/BD9hF0x/y9l2JXOOZLCse8c0PufCFYRb9rhIBZiyMrzY8z5V54LrLF/l7P/B4t28zivQS6RM83uRyEE3AKPN3rgUCYG8QgJN5z3TepXISD6rnOZOmb2lwbdTBtLNnwSirtY0Pog0joJp1wrAid8pIDXOHfQL2mZ0aIvvS12fzllwuCNROyWlY0ngT/Y1TsvrvtR8dp1K917yjO59U4YOOth5ZLcw3W3McDK4XkJmj7ax/fkC5819Cy4OG65J0GuBg5pTvxQYOOyrPPTdGEOjalfEmczjtATkDBQNiCYltar+pVlegnYO9/i0fTUJwLZoGw/B6DabxZRtcC7V4MIhyTJaM5LSw17SjXUwiMCPVDye4kESCUL22UaERiGa+9dVS1t1o3KvFR94DeAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
