travis:
  secure:
    BINSTAR_TOKEN: MxeJ7FoY696ml+BOYCQmkIxQ68tUClE9530e+WKsH5avEw3PIm4VXap+Auib+M+Zb9G4VFJfgzZI7J3T23aYTNcinoeMi74CcfS/82xDrZ08xG12j6f5Z33ERvygR6JvqqCNLg6wkJ7rtKHjUnwWTp1nWAjDOms0hVBJk9lmso87+wF3MrK7ZGn4wUxhlHc+RFUVlLfJ4a3GEgIj/bwKGW8tOIBfBMrBVRU7FCQibxPbLTXplYEx7WP6LQ3XUi9VkyLKErXowWNxx2H0bj9kwkEjLdYfYsYDqzIc0eZkw2UY5G7OKJFtGwODV2lPvHx6oFBZuYhTduzrNYuNAlqcRTK5BDKUaInGmslzsESk58F+sYjbRbN8qkJuqp5+jFQyDtRLrZa2P2fuuq12d6izP0e7lpctd9QDeR0NwmgQRrG75OltvUj9MAS5bmf7URaJW/jELOCt+3ILC9q12FIzTZwGRBILoQUGVMA4lCLX5fAzaNv3rmun+8qRTzByvXQl9qrIuJmzI38jaRSjonN73Z4dZvQx5Zqh+rEIPANAQaEDmxpFaO+EzJ5UsWxY1gM3UR6/KpR6DAzv9/rfVjWM++AcEkW0AswVSWjScsX5Ptf36IHd4LaMNcIMEhT59UeEiI37sMWQv9pum7J5+4E/U6LcM37yHS/r1TPX4HCW4Es=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
